### ISSUE TITLE
[PM] Goal

### ISSUE THREAD

**Issue by minaminao** [LayerXcom/load-balancing#3]
## Phase 1
- [ ] Formulate load balancing problems #2 
- [ ] Design algorithms to solve the problems

## Phase 2
- [ ] Experiment using the Eth1.0 transactions data
